---
- name: Uninstall Apache2 on Debian
  hosts: webservers
  become: true  # This enables privilege escalation (sudo)

  tasks:
    - name: Stop Apache2 service
      ansible.builtin.service:
        name: "{{mywebpackage}}"
        state: stopped
        enabled: false

    - name: Remove Apache2 package and its configuration files
      ansible.builtin.apt:
        name: "{{mywebpackage}}"
        state: absent
        purge: true # This ensures configuration files are also removed
        autoclean: true # Removes downloaded package files
        autoremove: true # Removes packages that were automatically installed to satisfy dependencies
