- name: Install and Start Apache2 on Debian
  hosts: mywebservers  # Replace with your inventory group/host  become: yes                 # Use privilege escalation (sudo) for installation and service control
  tasks:

    - name: Stop Apache2 service
      ansible.builtin.service:
        name: "{{mywebpackage}}"
        state: stopped      # Explicitly stop the service before removal
        enabled: no         # Ensure it won't start on the next reboot

    - name: Remove Apache2 package
      ansible.builtin.apt:
        name: "{{mywebpackage}}"
        state: absent       # The key to uninstallation!
