---
- name: Install and configure Apache2 on Debian
  hosts: mywebservers
  become: yes  # This activates sudo privileges for all tasks
  tasks:
    - name: Update apt package cache
      ansible.builtin.apt:
        update_cache: yes
      
    - name: Install apache2 package
      ansible.builtin.apt:
        name: "{{mywebpackage}}"
        state: latest
      
    - name: Ensure apache2 service is running and enabled
      ansible.builtin.service:
        name: "{{mywebpackage}}"
        state: started
        enabled: yes