- name: Install and Start Apache2 on Debian
  hosts: mywebservers  # Replace with your inventory group/host
  become: yes                 # Use privilege escalation (sudo) for installation and service control

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Apache2 package
      ansible.builtin.apt:
        name: "{{mywebpackage}}"
        state: present    # Ensures the package is installed (present)

    - name: Ensure Apache2 service is started and enabled
      ansible.builtin.service:
        name: "{{mywebpackage}}"
        state: started    # Ensures the service is running
        enabled: yes      # Ensures the service starts on boot