---
- hosts: mywebservers
  become: yes
  tasks:
     - name:  i want to isntall webserver 
       apt:
        name: "{{apache2}}"
        state: present
     - name: Ensure Apache2 service is running and enabled
       service:
        name: "{{apache2}}"
        state: started
        enabled: yes