---
- hosts: all
  become: yes
  tasks:
     - name:  Install Apache2 package
       apt:
        name: apache2
        state: present
     - name: Ensure Apache2 service is running and enabled
       service:
        name: apache2
        state: started
        enabled: yes